remove useRef type arg beacuse ci failing
```
Run yarn test
yarn run v1.22.5
$ DEBUG_PRINT_LIMIT=10000 jest
FAIL tests/Index.test.tsx
  ● Test suite failed to run

    pages/index.tsx:35:25 - error TS2531: Object is possibly 'null'.

    35             const url = inputRef.current.value
                               ~~~~~~~~~~~~~~~~
    pages/index.tsx:46:147 - error TS2540: Cannot assign to 'current' because it is a read-only property.

    46             <input className="block w-full my-4 p-4" placeholder="Paste YouTube link here" defaultValue="" ref={(c: HTMLInputElement) => inputRef.current = c} />
```