Unique party ids, auth, restyle, playback speed, other new features (#9)
* todo in readme

* add more to todo in readme

* anonymous auth works!

* update firebase path to party

* some hardcoded initial values but the concept works

* generate party id but user id still hardcoded

* auth provider and dynamic firebase owner!

* hasControl determined by session auth instead of query param

* redesign home page to support joining by code

* improve ts types – compiles now

* use builtin exported types for firebase.User

instead of custom object type

* improve jumbotron design

* update test. still needs firebase mock tho

* refactor firebase and try mocking

> TypeError: Cannot read property 'ref' of undefined

* use waitFor to get jest working

failing now but not erroring at least

* update test to support mocking important dependencies

* tests for join valid and invalid parties

* dynamic video width to fix mobile design

* mobile friendly home screen

* fix player size

* remove ded things

* Don't render children until we have an authorized user. Otherwise, queries are attempted before allowed, causing the video to never load

* cleanup completed readme todos

* support forcing custom playback rate speed